### ISSUE TITLE
Establish an identity

### ISSUE THREAD

**Issue by Jonghakseo** [kitchen-table/kitchen-table#17]
Before we make any further improvements to the product's roadmap, we need to think about what direction we want to take the product.

We need to think about our target audience in the short term and our revenue model in the long term.

**Comment by Jonghakseo** [comment]
Define identity as a tool for collaboration.
Here's what you need to consider
- Users: Production teams and stakeholders.
- Additional features:
  - Voice chat.
  - Authentication features. (github, google login)
  - Authentication key issuance and management process for organization configuration
- Monetization: SaaS cloud offering and other convenience features.
- License: MIT

**Comment by Jonghakseo** [comment]
- [ ] Need to organize your roadmap according to your established identity.

**Comment by Jonghakseo** [comment]
# Road Map (Draft)

## Basic features

- [ ] SDK import via script tag
- [ ] SDK basic config via script tag
  - [ ] Server endpoints
  - [ ] Toggle experimental features
  - [ ] Room id
- [ ] Chat
- [ ] Share mouse cursors position
- [ ] Share mouse click event position
- [ ] Share and invitation (need to think about how to implement. maybe related to authentication and security)
- [ ] Share doodlles

## Additianl features

- [ ] Auth / Sign-In (github? google?)
- [ ] Voice chat (web-rtc)
- [ ] Video chat (web-rtc)
- [ ] Comment on specific element

## Comportable features
- [ ] Toggle the mouse cursor and click event functionality on and off

## Dev only
- [ ] Implement expandable structure for additional APIs, plugins
- [ ] Setting up CI / CD

## Documentation
- [ ] Write README.md
- [ ] Add docs in project
  - [ ] Build docs app (via docusaurus?)
  - [ ] Hosting

**Comment by Jonghakseo** [comment]
@rhea-so 

I wrote a draft of roadmap. It is so rough, but i think we can start at this point.

Could you comment on this?

I think that the only point we need to meet and talk about is auth.
